spring:
  zipkin:
    enabled: true
    service.name: service2
    sender.type: web
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

  application:
    name: service2

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true