spring:
  zipkin:
    enabled: true
    service.name: service2
    sender.type: web
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

  application:
    name: service2


server:
  port: 7070

